version: '3'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: projeto
    environment:
      MONGO_URI: mongodb://root:root@db
      KEY_MASTER_JWT: 7PptwAWPnrmLJtZ6DkWhFLyf
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
    tty: true
    networks:
      - api-mongo-project
    volumes:
      - .:/home/node/app
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    tty: true
    networks:
      - api-mongo-project

networks:
   api-mongo-project: